---
- name: Upgrade Yum
  yum: update_cache=yes name=* state=latest
  tags: packages
- name: EPEL Release adding Source
  yum: update_cache=yes name={{ item }} state=latest
  with_items:
    - htop
    - fail2ban
    - openssl
